/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollectiveRouteImport } from './routes/collective'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated/directory'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEngagementsRouteImport } from './routes/_authenticated/engagements'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgramsMeRouteImport } from './routes/_authenticated/programs-me'
import { Route as MembershipIndexRouteImport } from './routes/membership.index'
import { Route as MembershipAgreementRouteImport } from './routes/membership.agreement'
import { Route as MembershipCorporateRouteImport } from './routes/membership.corporate'
import { Route as MembershipPersonalRouteImport } from './routes/membership.personal'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingAgreementRouteImport } from './routes/onboarding/agreement'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding/profile'
import { Route as OnboardingSetupRouteImport } from './routes/onboarding/setup'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsFoundersRouteImport } from './routes/programs.founders'
import { Route as ProgramsGiveNetworkRouteImport } from './routes/programs.give-network'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAgreementsRouteImport } from './routes/_authenticated/admin.agreements'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin.billing'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminInsightsRouteImport } from './routes/_authenticated/admin.insights'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminMissionsRouteImport } from './routes/_authenticated/admin.missions'
import { Route as AuthenticatedAdminOnboardingRouteImport } from './routes/_authenticated/admin.onboarding'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'
import { Route as AuthenticatedAdminProgramsRouteImport } from './routes/_authenticated/admin.programs'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminTgnMissionsRouteImport } from './routes/_authenticated/admin.tgn-missions'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAgreementResignRouteImport } from './routes/_authenticated/agreement.resign'
import { Route as AuthenticatedCompanyIndexRouteImport } from './routes/_authenticated/company.index'
import { Route as AuthenticatedCompanyDocumentsRouteImport } from './routes/_authenticated/company.documents'
import { Route as AuthenticatedCompanyEngagementsRouteImport } from './routes/_authenticated/company.engagements'
import { Route as AuthenticatedCompanyProfileRouteImport } from './routes/_authenticated/company.profile'
import { Route as AuthenticatedCompanyProgramsRouteImport } from './routes/_authenticated/company.programs'
import { Route as AuthenticatedCompanyTeamRouteImport } from './routes/_authenticated/company.team'
import { Route as AuthenticatedInsightsSlugRouteImport } from './routes/_authenticated/insights.$slug'
import { Route as AuthenticatedMembersMemberIdRouteImport } from './routes/_authenticated/members.$memberId'
import { Route as AuthenticatedMissionMissionIdRouteImport } from './routes/_authenticated/mission.$missionId'
import { Route as AuthenticatedNdaPartyIdRouteImport } from './routes/_authenticated/nda.$partyId'
import { Route as AuthenticatedPayInvoiceIdRouteImport } from './routes/_authenticated/pay.$invoiceId'
import { Route as ProgramsGiveNetworkIndexRouteImport } from './routes/programs.give-network.index'
import { Route as ProgramsGiveNetworkBack2basicsRouteImport } from './routes/programs.give-network.back2basics'
import { Route as ProgramsGiveNetworkImmersionRouteImport } from './routes/programs.give-network.immersion'
import { Route as ProgramsGiveNetworkMissionsRouteImport } from './routes/programs.give-network.missions'
import { Route as ProgramsGiveNetworkRemoteAdvisoryRouteImport } from './routes/programs.give-network.remote-advisory'
import { Route as AuthenticatedAdminCompaniesIndexRouteImport } from './routes/_authenticated/admin.companies.index'
import { Route as AuthenticatedAdminCompaniesCompanyIdRouteImport } from './routes/_authenticated/admin.companies.$companyId'
import { Route as AuthenticatedAdminMembersUserIdRouteImport } from './routes/_authenticated/admin.members.$userId'
import { Route as AuthenticatedDirectoryCompaniesCompanyIdRouteImport } from './routes/_authenticated/directory_.companies.$companyId'
import { Route as AuthenticatedMembersExecExecutiveIdRouteImport } from './routes/_authenticated/members.exec.$executiveId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectiveRoute = CollectiveRouteImport.update({
  id: '/collective',
  path: '/collective',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngagementsRoute =
  AuthenticatedEngagementsRouteImport.update({
    id: '/engagements',
    path: '/engagements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramsMeRoute = AuthenticatedProgramsMeRouteImport.update({
  id: '/programs-me',
  path: '/programs-me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MembershipIndexRoute = MembershipIndexRouteImport.update({
  id: '/membership/',
  path: '/membership/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipAgreementRoute = MembershipAgreementRouteImport.update({
  id: '/membership/agreement',
  path: '/membership/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipCorporateRoute = MembershipCorporateRouteImport.update({
  id: '/membership/corporate',
  path: '/membership/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipPersonalRoute = MembershipPersonalRouteImport.update({
  id: '/membership/personal',
  path: '/membership/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAgreementRoute = OnboardingAgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingSetupRoute = OnboardingSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsFoundersRoute = ProgramsFoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsGiveNetworkRoute = ProgramsGiveNetworkRouteImport.update({
  id: '/give-network',
  path: '/give-network',
  getParentRoute: () => ProgramsRoute,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAgreementsRoute =
  AuthenticatedAdminAgreementsRouteImport.update({
    id: '/admin/agreements',
    path: '/admin/agreements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/admin/applications',
    path: '/admin/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/admin/billing',
    path: '/admin/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/admin/documents',
    path: '/admin/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInsightsRoute =
  AuthenticatedAdminInsightsRouteImport.update({
    id: '/admin/insights',
    path: '/admin/insights',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMissionsRoute =
  AuthenticatedAdminMissionsRouteImport.update({
    id: '/admin/missions',
    path: '/admin/missions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOnboardingRoute =
  AuthenticatedAdminOnboardingRouteImport.update({
    id: '/admin/onboarding',
    path: '/admin/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/admin/pricing',
    path: '/admin/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProgramsRoute =
  AuthenticatedAdminProgramsRouteImport.update({
    id: '/admin/programs',
    path: '/admin/programs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/admin/requests',
    path: '/admin/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTgnMissionsRoute =
  AuthenticatedAdminTgnMissionsRouteImport.update({
    id: '/admin/tgn-missions',
    path: '/admin/tgn-missions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgreementResignRoute =
  AuthenticatedAgreementResignRouteImport.update({
    id: '/agreement/resign',
    path: '/agreement/resign',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyIndexRoute =
  AuthenticatedCompanyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyDocumentsRoute =
  AuthenticatedCompanyDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyEngagementsRoute =
  AuthenticatedCompanyEngagementsRouteImport.update({
    id: '/engagements',
    path: '/engagements',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyProfileRoute =
  AuthenticatedCompanyProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyProgramsRoute =
  AuthenticatedCompanyProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyTeamRoute =
  AuthenticatedCompanyTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedInsightsSlugRoute =
  AuthenticatedInsightsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedInsightsRoute,
  } as any)
const AuthenticatedMembersMemberIdRoute =
  AuthenticatedMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMissionMissionIdRoute =
  AuthenticatedMissionMissionIdRouteImport.update({
    id: '/mission/$missionId',
    path: '/mission/$missionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNdaPartyIdRoute = AuthenticatedNdaPartyIdRouteImport.update({
  id: '/nda/$partyId',
  path: '/nda/$partyId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayInvoiceIdRoute =
  AuthenticatedPayInvoiceIdRouteImport.update({
    id: '/pay/$invoiceId',
    path: '/pay/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProgramsGiveNetworkIndexRoute =
  ProgramsGiveNetworkIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProgramsGiveNetworkRoute,
  } as any)
const ProgramsGiveNetworkBack2basicsRoute =
  ProgramsGiveNetworkBack2basicsRouteImport.update({
    id: '/back2basics',
    path: '/back2basics',
    getParentRoute: () => ProgramsGiveNetworkRoute,
  } as any)
const ProgramsGiveNetworkImmersionRoute =
  ProgramsGiveNetworkImmersionRouteImport.update({
    id: '/immersion',
    path: '/immersion',
    getParentRoute: () => ProgramsGiveNetworkRoute,
  } as any)
const ProgramsGiveNetworkMissionsRoute =
  ProgramsGiveNetworkMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => ProgramsGiveNetworkRoute,
  } as any)
const ProgramsGiveNetworkRemoteAdvisoryRoute =
  ProgramsGiveNetworkRemoteAdvisoryRouteImport.update({
    id: '/remote-advisory',
    path: '/remote-advisory',
    getParentRoute: () => ProgramsGiveNetworkRoute,
  } as any)
const AuthenticatedAdminCompaniesIndexRoute =
  AuthenticatedAdminCompaniesIndexRouteImport.update({
    id: '/admin/companies/',
    path: '/admin/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCompaniesCompanyIdRoute =
  AuthenticatedAdminCompaniesCompanyIdRouteImport.update({
    id: '/admin/companies/$companyId',
    path: '/admin/companies/$companyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMembersUserIdRoute =
  AuthenticatedAdminMembersUserIdRouteImport.update({
    id: '/admin/members/$userId',
    path: '/admin/members/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDirectoryCompaniesCompanyIdRoute =
  AuthenticatedDirectoryCompaniesCompanyIdRouteImport.update({
    id: '/directory_/companies/$companyId',
    path: '/directory/companies/$companyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersExecExecutiveIdRoute =
  AuthenticatedMembersExecExecutiveIdRouteImport.update({
    id: '/members/exec/$executiveId',
    path: '/members/exec/$executiveId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/advisory': typeof AdvisoryRoute
  '/auth': typeof AuthRoute
  '/collective': typeof CollectiveRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/chat': typeof AuthenticatedChatRoute
  '/company': typeof AuthenticatedCompanyRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/engagements': typeof AuthenticatedEngagementsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/programs-me': typeof AuthenticatedProgramsMeRoute
  '/membership/agreement': typeof MembershipAgreementRoute
  '/membership/corporate': typeof MembershipCorporateRoute
  '/membership/personal': typeof MembershipPersonalRoute
  '/onboarding/agreement': typeof OnboardingAgreementRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/programs/founders': typeof ProgramsFoundersRoute
  '/programs/give-network': typeof ProgramsGiveNetworkRouteWithChildren
  '/sign/$token': typeof SignTokenRoute
  '/membership/': typeof MembershipIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/admin/agreements': typeof AuthenticatedAdminAgreementsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/missions': typeof AuthenticatedAdminMissionsRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/tgn-missions': typeof AuthenticatedAdminTgnMissionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agreement/resign': typeof AuthenticatedAgreementResignRoute
  '/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/company/engagements': typeof AuthenticatedCompanyEngagementsRoute
  '/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/company/programs': typeof AuthenticatedCompanyProgramsRoute
  '/company/team': typeof AuthenticatedCompanyTeamRoute
  '/insights/$slug': typeof AuthenticatedInsightsSlugRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/mission/$missionId': typeof AuthenticatedMissionMissionIdRoute
  '/nda/$partyId': typeof AuthenticatedNdaPartyIdRoute
  '/pay/$invoiceId': typeof AuthenticatedPayInvoiceIdRoute
  '/programs/give-network/back2basics': typeof ProgramsGiveNetworkBack2basicsRoute
  '/programs/give-network/immersion': typeof ProgramsGiveNetworkImmersionRoute
  '/programs/give-network/missions': typeof ProgramsGiveNetworkMissionsRoute
  '/programs/give-network/remote-advisory': typeof ProgramsGiveNetworkRemoteAdvisoryRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/company/': typeof AuthenticatedCompanyIndexRoute
  '/programs/give-network/': typeof ProgramsGiveNetworkIndexRoute
  '/admin/companies/$companyId': typeof AuthenticatedAdminCompaniesCompanyIdRoute
  '/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute
  '/directory/companies/$companyId': typeof AuthenticatedDirectoryCompaniesCompanyIdRoute
  '/members/exec/$executiveId': typeof AuthenticatedMembersExecExecutiveIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/companies/': typeof AuthenticatedAdminCompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/auth': typeof AuthRoute
  '/collective': typeof CollectiveRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/engagements': typeof AuthenticatedEngagementsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/programs-me': typeof AuthenticatedProgramsMeRoute
  '/membership/agreement': typeof MembershipAgreementRoute
  '/membership/corporate': typeof MembershipCorporateRoute
  '/membership/personal': typeof MembershipPersonalRoute
  '/onboarding/agreement': typeof OnboardingAgreementRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/programs/founders': typeof ProgramsFoundersRoute
  '/sign/$token': typeof SignTokenRoute
  '/membership': typeof MembershipIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/admin/agreements': typeof AuthenticatedAdminAgreementsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/missions': typeof AuthenticatedAdminMissionsRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/tgn-missions': typeof AuthenticatedAdminTgnMissionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agreement/resign': typeof AuthenticatedAgreementResignRoute
  '/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/company/engagements': typeof AuthenticatedCompanyEngagementsRoute
  '/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/company/programs': typeof AuthenticatedCompanyProgramsRoute
  '/company/team': typeof AuthenticatedCompanyTeamRoute
  '/insights/$slug': typeof AuthenticatedInsightsSlugRoute
  '/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/mission/$missionId': typeof AuthenticatedMissionMissionIdRoute
  '/nda/$partyId': typeof AuthenticatedNdaPartyIdRoute
  '/pay/$invoiceId': typeof AuthenticatedPayInvoiceIdRoute
  '/programs/give-network/back2basics': typeof ProgramsGiveNetworkBack2basicsRoute
  '/programs/give-network/immersion': typeof ProgramsGiveNetworkImmersionRoute
  '/programs/give-network/missions': typeof ProgramsGiveNetworkMissionsRoute
  '/programs/give-network/remote-advisory': typeof ProgramsGiveNetworkRemoteAdvisoryRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/company': typeof AuthenticatedCompanyIndexRoute
  '/programs/give-network': typeof ProgramsGiveNetworkIndexRoute
  '/admin/companies/$companyId': typeof AuthenticatedAdminCompaniesCompanyIdRoute
  '/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute
  '/directory/companies/$companyId': typeof AuthenticatedDirectoryCompaniesCompanyIdRoute
  '/members/exec/$executiveId': typeof AuthenticatedMembersExecExecutiveIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/advisory': typeof AdvisoryRoute
  '/auth': typeof AuthRoute
  '/collective': typeof CollectiveRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/company': typeof AuthenticatedCompanyRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/directory': typeof AuthenticatedDirectoryRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/engagements': typeof AuthenticatedEngagementsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/programs-me': typeof AuthenticatedProgramsMeRoute
  '/membership/agreement': typeof MembershipAgreementRoute
  '/membership/corporate': typeof MembershipCorporateRoute
  '/membership/personal': typeof MembershipPersonalRoute
  '/onboarding/agreement': typeof OnboardingAgreementRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/programs/founders': typeof ProgramsFoundersRoute
  '/programs/give-network': typeof ProgramsGiveNetworkRouteWithChildren
  '/sign/$token': typeof SignTokenRoute
  '/membership/': typeof MembershipIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/_authenticated/admin/agreements': typeof AuthenticatedAdminAgreementsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/missions': typeof AuthenticatedAdminMissionsRoute
  '/_authenticated/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/tgn-missions': typeof AuthenticatedAdminTgnMissionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/agreement/resign': typeof AuthenticatedAgreementResignRoute
  '/_authenticated/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/_authenticated/company/engagements': typeof AuthenticatedCompanyEngagementsRoute
  '/_authenticated/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/_authenticated/company/programs': typeof AuthenticatedCompanyProgramsRoute
  '/_authenticated/company/team': typeof AuthenticatedCompanyTeamRoute
  '/_authenticated/insights/$slug': typeof AuthenticatedInsightsSlugRoute
  '/_authenticated/members/$memberId': typeof AuthenticatedMembersMemberIdRoute
  '/_authenticated/mission/$missionId': typeof AuthenticatedMissionMissionIdRoute
  '/_authenticated/nda/$partyId': typeof AuthenticatedNdaPartyIdRoute
  '/_authenticated/pay/$invoiceId': typeof AuthenticatedPayInvoiceIdRoute
  '/programs/give-network/back2basics': typeof ProgramsGiveNetworkBack2basicsRoute
  '/programs/give-network/immersion': typeof ProgramsGiveNetworkImmersionRoute
  '/programs/give-network/missions': typeof ProgramsGiveNetworkMissionsRoute
  '/programs/give-network/remote-advisory': typeof ProgramsGiveNetworkRemoteAdvisoryRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/company/': typeof AuthenticatedCompanyIndexRoute
  '/programs/give-network/': typeof ProgramsGiveNetworkIndexRoute
  '/_authenticated/admin/companies/$companyId': typeof AuthenticatedAdminCompaniesCompanyIdRoute
  '/_authenticated/admin/members/$userId': typeof AuthenticatedAdminMembersUserIdRoute
  '/_authenticated/directory_/companies/$companyId': typeof AuthenticatedDirectoryCompaniesCompanyIdRoute
  '/_authenticated/members/exec/$executiveId': typeof AuthenticatedMembersExecExecutiveIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/admin/companies/': typeof AuthenticatedAdminCompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/advisory'
    | '/auth'
    | '/collective'
    | '/contact'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/privacy'
    | '/programs'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/account'
    | '/chat'
    | '/company'
    | '/dashboard'
    | '/directory'
    | '/documents'
    | '/engagements'
    | '/home'
    | '/insights'
    | '/profile'
    | '/programs-me'
    | '/membership/agreement'
    | '/membership/corporate'
    | '/membership/personal'
    | '/onboarding/agreement'
    | '/onboarding/profile'
    | '/onboarding/setup'
    | '/onboarding/welcome'
    | '/programs/founders'
    | '/programs/give-network'
    | '/sign/$token'
    | '/membership/'
    | '/onboarding/'
    | '/programs/'
    | '/admin/agreements'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/documents'
    | '/admin/insights'
    | '/admin/leads'
    | '/admin/missions'
    | '/admin/onboarding'
    | '/admin/pricing'
    | '/admin/programs'
    | '/admin/requests'
    | '/admin/tgn-missions'
    | '/admin/users'
    | '/agreement/resign'
    | '/company/documents'
    | '/company/engagements'
    | '/company/profile'
    | '/company/programs'
    | '/company/team'
    | '/insights/$slug'
    | '/members/$memberId'
    | '/mission/$missionId'
    | '/nda/$partyId'
    | '/pay/$invoiceId'
    | '/programs/give-network/back2basics'
    | '/programs/give-network/immersion'
    | '/programs/give-network/missions'
    | '/programs/give-network/remote-advisory'
    | '/admin/'
    | '/company/'
    | '/programs/give-network/'
    | '/admin/companies/$companyId'
    | '/admin/members/$userId'
    | '/directory/companies/$companyId'
    | '/members/exec/$executiveId'
    | '/api/public/payments/webhook'
    | '/admin/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisory'
    | '/auth'
    | '/collective'
    | '/contact'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/account'
    | '/chat'
    | '/dashboard'
    | '/directory'
    | '/documents'
    | '/engagements'
    | '/home'
    | '/insights'
    | '/profile'
    | '/programs-me'
    | '/membership/agreement'
    | '/membership/corporate'
    | '/membership/personal'
    | '/onboarding/agreement'
    | '/onboarding/profile'
    | '/onboarding/setup'
    | '/onboarding/welcome'
    | '/programs/founders'
    | '/sign/$token'
    | '/membership'
    | '/onboarding'
    | '/programs'
    | '/admin/agreements'
    | '/admin/announcements'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/documents'
    | '/admin/insights'
    | '/admin/leads'
    | '/admin/missions'
    | '/admin/onboarding'
    | '/admin/pricing'
    | '/admin/programs'
    | '/admin/requests'
    | '/admin/tgn-missions'
    | '/admin/users'
    | '/agreement/resign'
    | '/company/documents'
    | '/company/engagements'
    | '/company/profile'
    | '/company/programs'
    | '/company/team'
    | '/insights/$slug'
    | '/members/$memberId'
    | '/mission/$missionId'
    | '/nda/$partyId'
    | '/pay/$invoiceId'
    | '/programs/give-network/back2basics'
    | '/programs/give-network/immersion'
    | '/programs/give-network/missions'
    | '/programs/give-network/remote-advisory'
    | '/admin'
    | '/company'
    | '/programs/give-network'
    | '/admin/companies/$companyId'
    | '/admin/members/$userId'
    | '/directory/companies/$companyId'
    | '/members/exec/$executiveId'
    | '/api/public/payments/webhook'
    | '/admin/companies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/onboarding'
    | '/advisory'
    | '/auth'
    | '/collective'
    | '/contact'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/privacy'
    | '/programs'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/chat'
    | '/_authenticated/company'
    | '/_authenticated/dashboard'
    | '/_authenticated/directory'
    | '/_authenticated/documents'
    | '/_authenticated/engagements'
    | '/_authenticated/home'
    | '/_authenticated/insights'
    | '/_authenticated/profile'
    | '/_authenticated/programs-me'
    | '/membership/agreement'
    | '/membership/corporate'
    | '/membership/personal'
    | '/onboarding/agreement'
    | '/onboarding/profile'
    | '/onboarding/setup'
    | '/onboarding/welcome'
    | '/programs/founders'
    | '/programs/give-network'
    | '/sign/$token'
    | '/membership/'
    | '/onboarding/'
    | '/programs/'
    | '/_authenticated/admin/agreements'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/insights'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/missions'
    | '/_authenticated/admin/onboarding'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/programs'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/tgn-missions'
    | '/_authenticated/admin/users'
    | '/_authenticated/agreement/resign'
    | '/_authenticated/company/documents'
    | '/_authenticated/company/engagements'
    | '/_authenticated/company/profile'
    | '/_authenticated/company/programs'
    | '/_authenticated/company/team'
    | '/_authenticated/insights/$slug'
    | '/_authenticated/members/$memberId'
    | '/_authenticated/mission/$missionId'
    | '/_authenticated/nda/$partyId'
    | '/_authenticated/pay/$invoiceId'
    | '/programs/give-network/back2basics'
    | '/programs/give-network/immersion'
    | '/programs/give-network/missions'
    | '/programs/give-network/remote-advisory'
    | '/_authenticated/admin/'
    | '/_authenticated/company/'
    | '/programs/give-network/'
    | '/_authenticated/admin/companies/$companyId'
    | '/_authenticated/admin/members/$userId'
    | '/_authenticated/directory_/companies/$companyId'
    | '/_authenticated/members/exec/$executiveId'
    | '/api/public/payments/webhook'
    | '/_authenticated/admin/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  AdvisoryRoute: typeof AdvisoryRoute
  AuthRoute: typeof AuthRoute
  CollectiveRoute: typeof CollectiveRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  MembershipAgreementRoute: typeof MembershipAgreementRoute
  MembershipCorporateRoute: typeof MembershipCorporateRoute
  MembershipPersonalRoute: typeof MembershipPersonalRoute
  SignTokenRoute: typeof SignTokenRoute
  MembershipIndexRoute: typeof MembershipIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collective': {
      id: '/collective'
      path: '/collective'
      fullPath: '/collective'
      preLoaderRoute: typeof CollectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagements': {
      id: '/_authenticated/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof AuthenticatedEngagementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programs-me': {
      id: '/_authenticated/programs-me'
      path: '/programs-me'
      fullPath: '/programs-me'
      preLoaderRoute: typeof AuthenticatedProgramsMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/membership/': {
      id: '/membership/'
      path: '/membership'
      fullPath: '/membership/'
      preLoaderRoute: typeof MembershipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/agreement': {
      id: '/membership/agreement'
      path: '/membership/agreement'
      fullPath: '/membership/agreement'
      preLoaderRoute: typeof MembershipAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/corporate': {
      id: '/membership/corporate'
      path: '/membership/corporate'
      fullPath: '/membership/corporate'
      preLoaderRoute: typeof MembershipCorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/personal': {
      id: '/membership/personal'
      path: '/membership/personal'
      fullPath: '/membership/personal'
      preLoaderRoute: typeof MembershipPersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/agreement': {
      id: '/onboarding/agreement'
      path: '/agreement'
      fullPath: '/onboarding/agreement'
      preLoaderRoute: typeof OnboardingAgreementRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/setup': {
      id: '/onboarding/setup'
      path: '/setup'
      fullPath: '/onboarding/setup'
      preLoaderRoute: typeof OnboardingSetupRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/founders': {
      id: '/programs/founders'
      path: '/founders'
      fullPath: '/programs/founders'
      preLoaderRoute: typeof ProgramsFoundersRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/give-network': {
      id: '/programs/give-network'
      path: '/give-network'
      fullPath: '/programs/give-network'
      preLoaderRoute: typeof ProgramsGiveNetworkRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agreements': {
      id: '/_authenticated/admin/agreements'
      path: '/admin/agreements'
      fullPath: '/admin/agreements'
      preLoaderRoute: typeof AuthenticatedAdminAgreementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/insights': {
      id: '/_authenticated/admin/insights'
      path: '/admin/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AuthenticatedAdminInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/missions': {
      id: '/_authenticated/admin/missions'
      path: '/admin/missions'
      fullPath: '/admin/missions'
      preLoaderRoute: typeof AuthenticatedAdminMissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/onboarding': {
      id: '/_authenticated/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthenticatedAdminOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/programs': {
      id: '/_authenticated/admin/programs'
      path: '/admin/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AuthenticatedAdminProgramsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tgn-missions': {
      id: '/_authenticated/admin/tgn-missions'
      path: '/admin/tgn-missions'
      fullPath: '/admin/tgn-missions'
      preLoaderRoute: typeof AuthenticatedAdminTgnMissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agreement/resign': {
      id: '/_authenticated/agreement/resign'
      path: '/agreement/resign'
      fullPath: '/agreement/resign'
      preLoaderRoute: typeof AuthenticatedAgreementResignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company/': {
      id: '/_authenticated/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof AuthenticatedCompanyIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/documents': {
      id: '/_authenticated/company/documents'
      path: '/documents'
      fullPath: '/company/documents'
      preLoaderRoute: typeof AuthenticatedCompanyDocumentsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/engagements': {
      id: '/_authenticated/company/engagements'
      path: '/engagements'
      fullPath: '/company/engagements'
      preLoaderRoute: typeof AuthenticatedCompanyEngagementsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/profile': {
      id: '/_authenticated/company/profile'
      path: '/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof AuthenticatedCompanyProfileRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/programs': {
      id: '/_authenticated/company/programs'
      path: '/programs'
      fullPath: '/company/programs'
      preLoaderRoute: typeof AuthenticatedCompanyProgramsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/team': {
      id: '/_authenticated/company/team'
      path: '/team'
      fullPath: '/company/team'
      preLoaderRoute: typeof AuthenticatedCompanyTeamRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/insights/$slug': {
      id: '/_authenticated/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof AuthenticatedInsightsSlugRouteImport
      parentRoute: typeof AuthenticatedInsightsRoute
    }
    '/_authenticated/members/$memberId': {
      id: '/_authenticated/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthenticatedMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mission/$missionId': {
      id: '/_authenticated/mission/$missionId'
      path: '/mission/$missionId'
      fullPath: '/mission/$missionId'
      preLoaderRoute: typeof AuthenticatedMissionMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nda/$partyId': {
      id: '/_authenticated/nda/$partyId'
      path: '/nda/$partyId'
      fullPath: '/nda/$partyId'
      preLoaderRoute: typeof AuthenticatedNdaPartyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pay/$invoiceId': {
      id: '/_authenticated/pay/$invoiceId'
      path: '/pay/$invoiceId'
      fullPath: '/pay/$invoiceId'
      preLoaderRoute: typeof AuthenticatedPayInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/programs/give-network/': {
      id: '/programs/give-network/'
      path: '/'
      fullPath: '/programs/give-network/'
      preLoaderRoute: typeof ProgramsGiveNetworkIndexRouteImport
      parentRoute: typeof ProgramsGiveNetworkRoute
    }
    '/programs/give-network/back2basics': {
      id: '/programs/give-network/back2basics'
      path: '/back2basics'
      fullPath: '/programs/give-network/back2basics'
      preLoaderRoute: typeof ProgramsGiveNetworkBack2basicsRouteImport
      parentRoute: typeof ProgramsGiveNetworkRoute
    }
    '/programs/give-network/immersion': {
      id: '/programs/give-network/immersion'
      path: '/immersion'
      fullPath: '/programs/give-network/immersion'
      preLoaderRoute: typeof ProgramsGiveNetworkImmersionRouteImport
      parentRoute: typeof ProgramsGiveNetworkRoute
    }
    '/programs/give-network/missions': {
      id: '/programs/give-network/missions'
      path: '/missions'
      fullPath: '/programs/give-network/missions'
      preLoaderRoute: typeof ProgramsGiveNetworkMissionsRouteImport
      parentRoute: typeof ProgramsGiveNetworkRoute
    }
    '/programs/give-network/remote-advisory': {
      id: '/programs/give-network/remote-advisory'
      path: '/remote-advisory'
      fullPath: '/programs/give-network/remote-advisory'
      preLoaderRoute: typeof ProgramsGiveNetworkRemoteAdvisoryRouteImport
      parentRoute: typeof ProgramsGiveNetworkRoute
    }
    '/_authenticated/admin/companies/': {
      id: '/_authenticated/admin/companies/'
      path: '/admin/companies'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/companies/$companyId': {
      id: '/_authenticated/admin/companies/$companyId'
      path: '/admin/companies/$companyId'
      fullPath: '/admin/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/members/$userId': {
      id: '/_authenticated/admin/members/$userId'
      path: '/admin/members/$userId'
      fullPath: '/admin/members/$userId'
      preLoaderRoute: typeof AuthenticatedAdminMembersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory_/companies/$companyId': {
      id: '/_authenticated/directory_/companies/$companyId'
      path: '/directory/companies/$companyId'
      fullPath: '/directory/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedDirectoryCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/exec/$executiveId': {
      id: '/_authenticated/members/exec/$executiveId'
      path: '/members/exec/$executiveId'
      fullPath: '/members/exec/$executiveId'
      preLoaderRoute: typeof AuthenticatedMembersExecExecutiveIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCompanyRouteChildren {
  AuthenticatedCompanyDocumentsRoute: typeof AuthenticatedCompanyDocumentsRoute
  AuthenticatedCompanyEngagementsRoute: typeof AuthenticatedCompanyEngagementsRoute
  AuthenticatedCompanyProfileRoute: typeof AuthenticatedCompanyProfileRoute
  AuthenticatedCompanyProgramsRoute: typeof AuthenticatedCompanyProgramsRoute
  AuthenticatedCompanyTeamRoute: typeof AuthenticatedCompanyTeamRoute
  AuthenticatedCompanyIndexRoute: typeof AuthenticatedCompanyIndexRoute
}

const AuthenticatedCompanyRouteChildren: AuthenticatedCompanyRouteChildren = {
  AuthenticatedCompanyDocumentsRoute: AuthenticatedCompanyDocumentsRoute,
  AuthenticatedCompanyEngagementsRoute: AuthenticatedCompanyEngagementsRoute,
  AuthenticatedCompanyProfileRoute: AuthenticatedCompanyProfileRoute,
  AuthenticatedCompanyProgramsRoute: AuthenticatedCompanyProgramsRoute,
  AuthenticatedCompanyTeamRoute: AuthenticatedCompanyTeamRoute,
  AuthenticatedCompanyIndexRoute: AuthenticatedCompanyIndexRoute,
}

const AuthenticatedCompanyRouteWithChildren =
  AuthenticatedCompanyRoute._addFileChildren(AuthenticatedCompanyRouteChildren)

interface AuthenticatedInsightsRouteChildren {
  AuthenticatedInsightsSlugRoute: typeof AuthenticatedInsightsSlugRoute
}

const AuthenticatedInsightsRouteChildren: AuthenticatedInsightsRouteChildren = {
  AuthenticatedInsightsSlugRoute: AuthenticatedInsightsSlugRoute,
}

const AuthenticatedInsightsRouteWithChildren =
  AuthenticatedInsightsRoute._addFileChildren(
    AuthenticatedInsightsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEngagementsRoute: typeof AuthenticatedEngagementsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgramsMeRoute: typeof AuthenticatedProgramsMeRoute
  AuthenticatedAdminAgreementsRoute: typeof AuthenticatedAdminAgreementsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminInsightsRoute: typeof AuthenticatedAdminInsightsRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMissionsRoute: typeof AuthenticatedAdminMissionsRoute
  AuthenticatedAdminOnboardingRoute: typeof AuthenticatedAdminOnboardingRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminProgramsRoute: typeof AuthenticatedAdminProgramsRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminTgnMissionsRoute: typeof AuthenticatedAdminTgnMissionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAgreementResignRoute: typeof AuthenticatedAgreementResignRoute
  AuthenticatedMembersMemberIdRoute: typeof AuthenticatedMembersMemberIdRoute
  AuthenticatedMissionMissionIdRoute: typeof AuthenticatedMissionMissionIdRoute
  AuthenticatedNdaPartyIdRoute: typeof AuthenticatedNdaPartyIdRoute
  AuthenticatedPayInvoiceIdRoute: typeof AuthenticatedPayInvoiceIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCompaniesCompanyIdRoute: typeof AuthenticatedAdminCompaniesCompanyIdRoute
  AuthenticatedAdminMembersUserIdRoute: typeof AuthenticatedAdminMembersUserIdRoute
  AuthenticatedDirectoryCompaniesCompanyIdRoute: typeof AuthenticatedDirectoryCompaniesCompanyIdRoute
  AuthenticatedMembersExecExecutiveIdRoute: typeof AuthenticatedMembersExecExecutiveIdRoute
  AuthenticatedAdminCompaniesIndexRoute: typeof AuthenticatedAdminCompaniesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEngagementsRoute: AuthenticatedEngagementsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgramsMeRoute: AuthenticatedProgramsMeRoute,
  AuthenticatedAdminAgreementsRoute: AuthenticatedAdminAgreementsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminInsightsRoute: AuthenticatedAdminInsightsRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminMissionsRoute: AuthenticatedAdminMissionsRoute,
  AuthenticatedAdminOnboardingRoute: AuthenticatedAdminOnboardingRoute,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
  AuthenticatedAdminProgramsRoute: AuthenticatedAdminProgramsRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminTgnMissionsRoute: AuthenticatedAdminTgnMissionsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAgreementResignRoute: AuthenticatedAgreementResignRoute,
  AuthenticatedMembersMemberIdRoute: AuthenticatedMembersMemberIdRoute,
  AuthenticatedMissionMissionIdRoute: AuthenticatedMissionMissionIdRoute,
  AuthenticatedNdaPartyIdRoute: AuthenticatedNdaPartyIdRoute,
  AuthenticatedPayInvoiceIdRoute: AuthenticatedPayInvoiceIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCompaniesCompanyIdRoute:
    AuthenticatedAdminCompaniesCompanyIdRoute,
  AuthenticatedAdminMembersUserIdRoute: AuthenticatedAdminMembersUserIdRoute,
  AuthenticatedDirectoryCompaniesCompanyIdRoute:
    AuthenticatedDirectoryCompaniesCompanyIdRoute,
  AuthenticatedMembersExecExecutiveIdRoute:
    AuthenticatedMembersExecExecutiveIdRoute,
  AuthenticatedAdminCompaniesIndexRoute: AuthenticatedAdminCompaniesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OnboardingRouteRouteChildren {
  OnboardingAgreementRoute: typeof OnboardingAgreementRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingSetupRoute: typeof OnboardingSetupRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingAgreementRoute: OnboardingAgreementRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingSetupRoute: OnboardingSetupRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface ProgramsGiveNetworkRouteChildren {
  ProgramsGiveNetworkBack2basicsRoute: typeof ProgramsGiveNetworkBack2basicsRoute
  ProgramsGiveNetworkImmersionRoute: typeof ProgramsGiveNetworkImmersionRoute
  ProgramsGiveNetworkMissionsRoute: typeof ProgramsGiveNetworkMissionsRoute
  ProgramsGiveNetworkRemoteAdvisoryRoute: typeof ProgramsGiveNetworkRemoteAdvisoryRoute
  ProgramsGiveNetworkIndexRoute: typeof ProgramsGiveNetworkIndexRoute
}

const ProgramsGiveNetworkRouteChildren: ProgramsGiveNetworkRouteChildren = {
  ProgramsGiveNetworkBack2basicsRoute: ProgramsGiveNetworkBack2basicsRoute,
  ProgramsGiveNetworkImmersionRoute: ProgramsGiveNetworkImmersionRoute,
  ProgramsGiveNetworkMissionsRoute: ProgramsGiveNetworkMissionsRoute,
  ProgramsGiveNetworkRemoteAdvisoryRoute:
    ProgramsGiveNetworkRemoteAdvisoryRoute,
  ProgramsGiveNetworkIndexRoute: ProgramsGiveNetworkIndexRoute,
}

const ProgramsGiveNetworkRouteWithChildren =
  ProgramsGiveNetworkRoute._addFileChildren(ProgramsGiveNetworkRouteChildren)

interface ProgramsRouteChildren {
  ProgramsFoundersRoute: typeof ProgramsFoundersRoute
  ProgramsGiveNetworkRoute: typeof ProgramsGiveNetworkRouteWithChildren
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsFoundersRoute: ProgramsFoundersRoute,
  ProgramsGiveNetworkRoute: ProgramsGiveNetworkRouteWithChildren,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  AdvisoryRoute: AdvisoryRoute,
  AuthRoute: AuthRoute,
  CollectiveRoute: CollectiveRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  MembershipAgreementRoute: MembershipAgreementRoute,
  MembershipCorporateRoute: MembershipCorporateRoute,
  MembershipPersonalRoute: MembershipPersonalRoute,
  SignTokenRoute: SignTokenRoute,
  MembershipIndexRoute: MembershipIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
